### ISSUE TITLE
Alles gaat stuk hier

### ISSUE THREAD

**Issue by AciDCooL** [ThisisDaan/iXecSync#1]
TVSHOW - Marvel's The Inhumans
SEARCH API URL - https://api.themoviedb.org/3/search/tv?api_key=8330115f9230acfdbe0e5470649f6602&query=Marvel%27s+The+Inhumans
TVSHOW - Money Heist
SEARCH API URL - https://api.themoviedb.org/3/search/tv?api_key=8330115f9230acfdbe0e5470649f6602&query=Money+Heist
[{'id': '5c9655269251416b33f32459', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': 'cQYvQIrM1FY', 'name': 'La Casa De Papel (Money Heist) TV Series Trailer', 'site': 'YouTube', 'size': 1080, 'type': 'Trailer'}, {'id': '5e974edd097c4900120a4229', 'iso_639_1': 'en', 'iso_3166_1': 
'US', 'key': 'ZAXA1DV4dtI', 'name': 'Money Heist - Part 2 | Official Trailer | Netflix', 'site': 'YouTube', 'size': 1080, 'type': 'Trailer'}, {'id': '5e974eaed1444300124fd952', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': 'TFJwUwnShnA', 'name': 'Money Heist: Part 3 | Official 
Trailer | Netflix', 'site': 'YouTube', 'size': 1080, 'type': 'Trailer'}, {'id': '5e974e2bb339030015a0fe21', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': 'p_PJbmrX4uk', 'name': 'Money Heist: Part 4 | Official Trailer | Netflix', 'site': 'YouTube', 'size': 1080, 'type': 'Trailer'}]
Saving movie to DB - Zoey's Extraordinary Playlist - S01E07 - Zoey's Extraordinary Confession WEBDL-1080p-METCON.mp4
Downloading poster
error no response
TVSHOW - The Oldenheim 12
SEARCH API URL - https://api.themoviedb.org/3/search/tv?api_key=8330115f9230acfdbe0e5470649f6602&query=The+Oldenheim+12
TVSHOW - VICE
SEARCH API URL - https://api.themoviedb.org/3/search/tv?api_key=8330115f9230acfdbe0e5470649f6602&query=VICE
Round #2 - VICE / Miami Vice - Matching with 0.5714285714285714
[{'id': '5d3b89f32667780010c4848d', 'iso_639_1': 'en', 'iso_3166_1': 'US', 'key': 'UT18_goPvHc', 'name': 'VICE: Season 1: What Is VICE? Featurette | HBO', 'site': 'YouTube', 'size': 720, 'type': 'Featurette'}]
Saving movie to DB - Zoey's Extraordinary Playlist - S01E07 - Zoey's Extraordinary Confession WEBDL-1080p-METCON.mp4
Downloading poster
error no response
TVSHOW - -=Series=-
SEARCH API URL - https://api.themoviedb.org/3/search/tv?api_key=8330115f9230acfdbe0e5470649f6602&query=-%3DSeries%3D-
Scanned file - video.mkv
Traceback (most recent call last):
  File "C:\python3\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\python3\Lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\python3\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\python3\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\python3\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\python3\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\python3\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\python3\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\python3\Lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\-Coding-\iXecSync\app.py", line 733, in scanning_tmdb
    tmdb.scan_library()
  File "C:\-Coding-\iXecSync\tmdb.py", line 24, in scan_library
    new_scan_library_movie(library)
  File "C:\-Coding-\iXecSync\tmdb.py", line 49, in new_scan_library_movie
    release_date = name.split(" (")[1].replace(")", "")
IndexError: list index out of range

**Comment by ThisisDaan** [comment]
Seems like an user issue. Issue closed
